name: Checking

on: push

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:

      - name: Setup Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Deno
        uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2
        with:
          deno-version: v2.x

      - name: Dry Run
        run: deno publish --dry-run --allow-slow-types

      - name: Tests
        run: deno test --quiet --coverage --parallel ./specs

      - name: Coverage
        run: |-
          deno coverage --exclude=./specs --lcov --output=cov.lcov
          deno coverage --exclude=./specs

      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          files: cov.lcov
          use_oidc: true

