name: Checking

on: push

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-slim
    timeout-minutes: 3

    steps:

      - name: Setup Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2.x

      - name: Dry Run
        run: deno publish --dry-run --allow-slow-types

      - name: Tests
        run: deno test --quiet --coverage --parallel ./specs

      - name: Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          files: coverage/lcov.info
          use_oidc: true

