name: Checking

on: push

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-slim
    timeout-minutes: 3

    steps:

      - name: Setup Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: v2.x

      - name: Dry Run
        run: deno publish --dry-run --allow-slow-types

      - name: Tests
        run: deno test --quiet --coverage --parallel ./specs

      - name: Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: coverage/lcov.info
          use_oidc: true

